### ISSUE TITLE
トークン配布画面の項目名見直し

### ISSUE THREAD

**Issue by Keita-Shimizu135** [zkcream/zkcream-interface#5]
トークン配布モーダル画面での項目名は「Voter's Address」などがよいか

![image](https://user-images.githubusercontent.com/73087577/131223777-776e8d0c-ba33-4af0-84c7-55cc6a08c572.png)

**Comment by kazuakiishiguro** [comment]
Fixed at a32d37439786b7dee295cd3a36c404d7b8f65e2a
