### ISSUE TITLE
選挙画面（コーディネーター）仕様確認

### ISSUE THREAD

**Issue by Keita-Shimizu135** [zkcream/zkcream-interface#7]
コーディネーターはwithdrawできないと思われるが、ボタンは必要か

![image](https://user-images.githubusercontent.com/73087577/131235976-bd3bc68e-3a2e-4cab-a749-dd6648ebc5b4.png)

**Comment by kazuakiishiguro** [comment]
コーディネーターがWithdrawをするのでこちらは問題ありません。
