### ISSUE TITLE
Tally Hashが未集計の場合、その旨を表示する

### ISSUE THREAD

**Issue by Keita-Shimizu135** [zkcream/zkcream-interface#8]
現状では、投票が未集計の場合Tally Hashは空欄になっているが、未集計である旨を表示する方が親切

![image](https://user-images.githubusercontent.com/73087577/131236014-3b8e118b-89d9-446e-bb79-4212229e1378.png)

**Comment by kazuakiishiguro** [comment]
Fixed at f1aeb3d769cbdaadba5631a1b85845c33657df09
